### PR TITLE
Port deployment model to ARM mode

### PR DESCRIPTION
**Pull request by chazkii**
Please don't merge just yet, I want to start a conversation and see if you guys are already working on it I've run into an issue with automation as outlined in the README. Reading through the MSDN forums, it looks like [they won't get rid of Classic deployment model anytime soon](https://social.technet.microsoft.com/Forums/lync/en-US/7b94514d-3df8-49aa-8c6d-f60e312c805f/azure-service-manager-eol-timeline?forum=windowsazuremanagement) but are encouraging migration to Resource Manager model. Let me know what I can do to help and what I need to change to get this inline with your standards.

---

This change is [Reviewable](https://reviewable.io/reviews/weaveworks/weave-kubernetes-coreos-azure/4)

### CODE REVIEW

**Comment by errordeveloper** [comment]
@chuckus this is really a great start, thank you very much for your contribution! Please let me know if you have made any progress more recently.

**Comment by phagunbaya** [comment]
Is there any plan to close this PR ?

**Comment by chazkii** [comment]
@errordeveloper Sorry, I haven't followed up as I've moved away from Kubernetes and use Docker Compose/Cloud. I still use Azure, and I realise if I were to do this, the best way is to actually use the Azure XML templates for defining resources as opposed to the using the Azure CLI flags.

**Comment by errordeveloper** [comment]
@chuckus thanks for the update. @phagunbaya would you like to discuss anything on this subject?

**Comment by phagunbaya** [comment]
@errordeveloper : Yes. How do you use azure templates for bringing up an kubernetes cluster ? Any references ?

**Comment by errordeveloper** [comment]
@phagunbaya I haven't tried ARM yet, but I'd advise you take a look at our more recent project - [Kubernetes Anywhere](https://github.com/weaveworks/kubernetes-anywhere), it should be much easier to make it run on any cloud using whatever provisioning tools you might like to use.

**Comment by phagunbaya** [comment]
@errordeveloper : Awesome ! I'll give it a try.

**Comment by phagunbaya** [comment]
@errordeveloper : I was trying out kubernetes installation using the guide for "Kubernetes Anywhere". But when I start `weaveworks/kubernetes-anywhere:etcd` container. I get below logs and it exits.

$ sudo docker run -d -e ETCD_CLUSTER_SIZE=2 --name=etcd1 weaveworks/kubernetes-anywhere:etcd

```
+ sed s|\([1-9]*\)|etcd\1=http://etcd\1:2380|g
+ seq -s , 1 2
+ ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
+ export ETCD_INITIAL_CLUSTER
+ hostname -s
+ n=325deb1ce24b c=http://325deb1ce24b:2379 p=http://325deb1ce24b:2380
+ exec etcd --name=325deb1ce24b --listen-peer-urls=http://325deb1ce24b:2380 --initial-advertise-peer-urls=http://325deb1ce24b:2380 --listen-client-urls=http://325deb1ce24b:2379 --advertise-client-urls=http://325deb1ce24b:2379
2016-05-01 10:06:21.580909 I | flags: recognized and used environment variable ETCD_INITIAL_CLUSTER=etcd1=http://etcd1:2380,etcd2=http://etcd2:2380
2016-05-01 10:06:21.581001 W | flags: unrecognized environment variable ETCD_CLUSTER_SIZE=2
2016-05-01 10:06:21.581043 I | etcdmain: etcd Version: 2.2.1
2016-05-01 10:06:21.581055 I | etcdmain: Git SHA: 75f8282
2016-05-01 10:06:21.581065 I | etcdmain: Go Version: go1.5.1
2016-05-01 10:06:21.581075 I | etcdmain: Go OS/Arch: linux/amd64
2016-05-01 10:06:21.581095 I | etcdmain: setting maximum number of CPUs to 2, total number of available CPUs is 2
2016-05-01 10:06:21.581108 W | etcdmain: no data-dir provided, using default data-dir ./325deb1ce24b.etcd
2016-05-01 10:06:21.581281 I | etcdmain: listening for peers on http://325deb1ce24b:2380
2016-05-01 10:06:21.581327 I | etcdmain: listening for client requests on http://325deb1ce24b:2379
2016-05-01 10:06:21.581463 I | etcdmain: stopping listening for client requests on http://325deb1ce24b:2379
2016-05-01 10:06:21.581489 I | etcdmain: stopping listening for peers on http://325deb1ce24b:2380
2016-05-01 10:06:21.581506 C | etcdmain: couldn't find local name "325deb1ce24b" in the initial cluster configuration
```

**Comment by errordeveloper** [comment]
@phagunbaya this is because of `sudo` not passing `DOCKER_HOST` environment variable, which is how `sudo` works.

Try this:

```
$ sudo -s
# eval $(weave env)
# docker run -d -e ETCD_CLUSTER_SIZE=<N> --name=etcd1 weaveworks/kubernetes-anywhere:etcd
```

Also, if you take a look at [etcd docs](https://coreos.com/etcd/docs/latest/admin_guide.html), you will find out that should set `N` to an odd number.

**Comment by errordeveloper** [comment]
@phagunbaya it's best if you file any issues like this directly in the repo where they belog: https://github.com/weaveworks/weave-kubernetes-anywhere/issues/new

**Pull request closed without merging**
